// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Test.Models;

public partial class ModulePermission
{
    public int Id { get; set; }

    public int ModuleId { get; set; }

    public string PermissionsJson { get; set; }

    public virtual Module Module { get; set; }
}