// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Test.Models;

public partial class Role
{
    public int Id { get; set; }

    public string RoleName { get; set; }

    public int? ParentRoleId { get; set; }

    public string DisplayName { get; set; }

    public virtual ICollection<Role> InverseParentRole { get; set; } = new List<Role>();

    public virtual Role ParentRole { get; set; }

    public virtual ICollection<RoleClaim> RoleClaims { get; set; } = new List<RoleClaim>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}