// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Test.Models;

public partial class User
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string MobileNumber { get; set; }

    public string PasswordHash { get; set; }

    public int RoleId { get; set; }

    public string VerificationCode { get; set; }

    public DateTime? VerificationCodeGenerationTime { get; set; }

    public DateTime? VerificationCodeValidationTime { get; set; }

    public string Otp { get; set; }

    public DateTime? OtpExpireTime { get; set; }

    public DateTime? ResendOtpTime { get; set; }

    public DateTime? OtpValidatedOn { get; set; }

    public string RefreshToken { get; set; }

    public DateTime? RefreshTokenExpireTime { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsVerified { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedBy { get; set; }

    public int? ModifiedBy { get; set; }

    public virtual Role Role { get; set; }
}